---
- name: Gather service facts
  tags: [systemd-resolved, resolved, dns]
  service_facts:

- import_tasks: install.yml
  tags: [systemd-resolved, resolved, dns]

- include_tasks: disable_other_resolvers.yml
  tags: [systemd-resolved, resolved, dns]
  when:
    - systemd_resolved_disable_other_resolvers
    - systemd_resolved_service_enabled or systemd_resolved_service_state != 'stopped'

- import_tasks: configure.yml
  tags: [systemd-resolved, resolved, dns]

- import_tasks: service.yml
  tags: [systemd-resolved, resolved, dns]
