---
- name: reload systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  when: systemd_resolved_service_state != 'stopped'

- name: restart networkmanager
  systemd:
    name: NetworkManager
    state: restarted
