---
- name: reload systemd-resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
  when:
    - systemd_resolved_service_restart_on_change | bool
    - systemd_resolved_service_state != 'stopped'

- name: restart networkmanager
  ansible.builtin.systemd:
    name: NetworkManager
    state: restarted
